### ISSUE TITLE
Feedback from Florence and Dora

### ISSUE THREAD

**Issue by jasmineqyj** [UBC-MDS/DSCI522_GR406#38]
1. Model is answering multiple research questions (more than just the research question listed in our report) - make it more clear?
2. Inference: hypothesis test instead of fitting a model
3. Heat map: change colour or add annotations (numbers)
4. Explain more about why we are including confounding variables in the model
5. Result table not clear / highlight result table

**Comment by zanderhinton** [comment]
Concerns addressed:

- Made research question clear, interested in both time of day and day of week
- Laying out all variables, and use of linear model to explain modelling process
- Adjusted scale and colours in heat map
- Simplified result table and made variable names more readable
