### ISSUE TITLE
Milestone 3 Peer Feedback

### ISSUE THREAD

**Issue by jamesh4** [UBC-MDS/DSCI522_GR406#40]
+ Confounding variable of location could be presented differently or eliminated. Makes the results long and complex and harder to interpret. Doesn't directly relate to the research question.

+ Add description or instructions on how to interpret the summary table better.

+ Use scientific notation for p value so we don't have a bunch of 0 values.

+ Change scale of heat-map to make the differences more differentiable.

**Comment by zanderhinton** [comment]
- Simplified table to only include the variables of interest
- Made table variable names more readable
- Used scientific notation for p value
- Changed scale and colour scheme of heat map
