### ISSUE TITLE
Milestone 2 Feedback: Reasoning

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/DSCI522_GR406#42]
I think it is very important that you make clear that your claims are not causal, but merely correlational. You have done this already, great job!

Really great that you translated the statistical significance to economic implications and interpreted your results this way as well. Well done!

I would suggest renaming the "Future Directions and Implementations" to "Limitations and Future Directions" as that fits better to what you explain in that section.

**Comment by zanderhinton** [comment]
Renamed final section in report.
